.\" Automatically generated by Pandoc 3.1.1
.\"
.\" Define V font for inline verbatim, using C font in formats
.\" that render this, and otherwise B font.
.ie "\f[CB]x\f[]"x" \{\
. ftr V B
. ftr VI BI
. ftr VB B
. ftr VBI BI
.\}
.el \{\
. ftr V CR
. ftr VI CI
. ftr VB CB
. ftr VBI CBI
.\}
.TH "Promise.Promise" "JS" "2023-06-02" "JavaScript" "JavaScript Reference Manual"
.hy
.SH Synopsis
.PP
The \f[B]\f[VB]Promise()\f[B]\f[R] constructor creates \f[V]Promise\f[R]
objects.
It is primarily used to wrap callback-based APIs that do not already
support promises.
.SH Syntax
.IP
.nf
\f[C]
new Promise(executor)
\f[R]
.fi
.RS
.PP
\f[B]Note:\f[R] \f[V]Promise()\f[R] can only be constructed with
\f[V]new\f[R].
Attempting to call it without \f[V]new\f[R] throws a
\f[V]TypeError\f[R].
.RE
.SS Parameters
.IP \[bu] 2
\f[V]executor\f[R]
.RS 2
.IP \[bu] 2
A \f[V]function\f[R] to be executed by the constructor.
It receives two functions as parameters: \f[V]resolveFunc\f[R] and
\f[V]rejectFunc\f[R].
Any errors thrown in the \f[V]executor\f[R] will cause the promise to be
rejected, and the return value will be neglected.
The semantics of \f[V]executor\f[R] are detailed below.
.RE
.SS Return value
.PP
When called via \f[V]new\f[R], the \f[V]Promise\f[R] constructor returns
a promise object.
The promise object will become \f[I]resolved\f[R] when either of the
functions \f[V]resolveFunc\f[R] or \f[V]rejectFunc\f[R] are invoked.
Note that if you call \f[V]resolveFunc\f[R] or \f[V]rejectFunc\f[R] and
pass another \f[V]Promise\f[R] object as an argument, it can be said to
be \[lq]resolved\[rq], but still not \[lq]settled\[rq].
See the Promise description for more explanation.
.SH Description
.PP
Traditionally (before promises), asynchronous tasks were designed as
callbacks.
.IP
.nf
\f[C]
readFile(\[dq]./data.txt\[dq], (error, result) => {
  // This callback will be called when the task is done, with the
  // final \[ga]error\[ga] or \[ga]result\[ga]. Any operation dependent on the
  // result must be defined within this callback.
});
// Code here is immediately executed after the \[ga]readFile\[ga] request
// is fired. It does not wait for the callback to be called, hence
// making \[ga]readFile\[ga] \[dq]asynchronous\[dq].
\f[R]
.fi
.PP
To take advantage of the readability improvement and language features
offered by promises, the \f[V]Promise()\f[R] constructor allows one to
transform the callback-based API to a promise-based one.
.RS
.PP
\f[B]Note:\f[R] If your task is already promise-based, you likely do not
need the \f[V]Promise()\f[R] constructor.
.RE
.PP
The \f[V]executor\f[R] is custom code that ties an outcome in a callback
to a promise.
You, the programmer, write the \f[V]executor\f[R].
Its signature is expected to be:
.IP
.nf
\f[C]
function executor(resolveFunc, rejectFunc) {
  // Typically, some asynchronous operation that accepts a callback,
  // like the \[ga]readFile\[ga] function above
}
\f[R]
.fi
.PP
\f[V]resolveFunc\f[R] and \f[V]rejectFunc\f[R] are also functions, and
you can give them whatever actual names you want.
Their signatures are simple: they accept a single parameter of any type.
.IP
.nf
\f[C]
resolveFunc(value); // call on resolved
rejectFunc(reason); // call on rejected
\f[R]
.fi
.PP
The \f[V]value\f[R] parameter passed to \f[V]resolveFunc\f[R] can be
another promise object, in which case the newly constructed
promise\[cq]s state will be \[lq]locked in\[rq] to the promise passed
(as part of the resolution promise).
The \f[V]rejectFunc\f[R] has semantics close to the \f[V]throw\f[R]
statement, so \f[V]reason\f[R] is typically an \f[V]Error\f[R] instance.
If either \f[V]value\f[R] or \f[V]reason\f[R] is omitted, the promise is
fulfilled/rejected with \f[V]undefined\f[R].
.PP
The \f[V]executor\f[R]\[cq]s completion state has limited effect on the
promise\[cq]s state:
.IP \[bu] 2
The \f[V]executor\f[R] return value is ignored.
\f[V]return\f[R] statements within the \f[V]executor\f[R] merely impact
control flow and alter whether a part of the function is executed, but
do not have any impact on the promise\[cq]s fulfillment value.
If \f[V]executor\f[R] exits and it\[cq]s impossible for
\f[V]resolveFunc\f[R] or \f[V]rejectFunc\f[R] to be called in the future
(for example, there are no async tasks scheduled), then the promise
remains pending forever.
.IP \[bu] 2
If an error is thrown in the \f[V]executor\f[R], the promise is
rejected, unless \f[V]resolveFunc\f[R] or \f[V]rejectFunc\f[R] has
already been called.
.RS
.PP
\f[B]Note:\f[R] The existence of pending promises does not prevent the
program from exiting.
If the event loop is empty, the program exits despite any pending
promises (because those are necessarily forever-pending).
.RE
.PP
Here\[cq]s a summary of the typical flow:
.IP "1." 3
At the time when the constructor generates the new \f[V]Promise\f[R]
object, it also generates a corresponding pair of functions for
\f[V]resolveFunc\f[R] and \f[V]rejectFunc\f[R]; these are
\[lq]tethered\[rq] to the \f[V]Promise\f[R] object.
.IP "2." 3
\f[V]executor\f[R] typically wraps some asynchronous operation which
provides a callback-based API.
The callback (the one passed to the original callback-based API) is
defined within the \f[V]executor\f[R] code, so it has access to the
\f[V]resolveFunc\f[R] and \f[V]rejectFunc\f[R].
.IP "3." 3
The \f[V]executor\f[R] is called synchronously (as soon as the
\f[V]Promise\f[R] is constructed) with the \f[V]resolveFunc\f[R] and
\f[V]rejectFunc\f[R] functions as arguments.
.IP "4." 3
The code within the \f[V]executor\f[R] has the opportunity to perform
some operation.
The eventual completion of the asynchronous task is communicated with
the promise instance via the side effect caused by \f[V]resolveFunc\f[R]
or \f[V]rejectFunc\f[R].
The side effect is that the \f[V]Promise\f[R] object becomes
\[lq]resolved\[rq].
.RS 4
.IP \[bu] 2
If \f[V]resolveFunc\f[R] is called first, the value passed will be
resolved.
The promise may stay pending (in case another thenable is passed),
become fulfilled (in most cases where a non-thenable value is passed),
or become rejected (in case of an invalid resolution value).
.IP \[bu] 2
If \f[V]rejectFunc\f[R] is called first, the promise instantly becomes
rejected.
.IP \[bu] 2
Once one of the resolving functions (\f[V]resolveFunc\f[R] or
\f[V]rejectFunc\f[R]) is called, the promise stays resolved.
Only the first call to \f[V]resolveFunc\f[R] or \f[V]rejectFunc\f[R]
affects the promise\[cq]s eventual state, and subsequent calls to either
function can neither change the fulfillment value/rejection reason nor
toggle its eventual state from \[lq]fulfilled\[rq] to \[lq]rejected\[rq]
or opposite.
.IP \[bu] 2
If \f[V]executor\f[R] exits by throwing an error, then the promise is
rejected.
However, the error is ignored if one of the resolving functions has
already been called (so that the promise is already resolved).
.IP \[bu] 2
Resolving the promise does not necessarily cause the promise to become
fulfilled or rejected (i.e.\ settled).
The promise may still be pending because it\[cq]s resolved with another
thenable, but its eventual state will match that of the resolved
thenable.
.RE
.IP "5." 3
Once the promise settles, it (asynchronously) invokes any further
handlers associated through \f[V]then()\f[R], \f[V]catch()\f[R], or
\f[V]finally()\f[R].
The eventual fulfillment value or rejection reason is passed to the
invocation of fulfillment and rejection handlers as an input parameter
(see Chained Promises).
.PP
For example, the callback-based \f[V]readFile\f[R] API above can be
transformed into a promise-based one.
.IP
.nf
\f[C]
const readFilePromise = (path) =>
  new Promise((resolve, reject) => {
    readFile(path, (error, result) => {
      if (error) {
        reject(error);
      } else {
        resolve(result);
      }
    });
  });

readFilePromise(\[dq]./data.txt\[dq])
  .then((result) => console.log(result))
  .catch((error) => console.error(\[dq]Failed to read data\[dq]));
\f[R]
.fi
.SS Resolver function
.PP
The resolver function \f[V]resolveFunc\f[R] has the following behaviors:
.IP \[bu] 2
If it\[cq]s called with the same value as the newly created promise (the
promise it\[cq]s \[lq]tethered to\[rq]), the promise is rejected with a
\f[V]TypeError\f[R].
.IP \[bu] 2
If it\[cq]s called with a non-thenable value (a primitive, or an object
whose \f[V]then\f[R] property is not callable, including when the
property is not present), the promise is immediately fulfilled with that
value.
.IP \[bu] 2
If it\[cq]s called with a thenable value (including another
\f[V]Promise\f[R] instance), then the thenable\[cq]s \f[V]then\f[R]
method is saved and called in the future (it\[cq]s always called
asynchronously).
The \f[V]then\f[R] method will be called with two callbacks, which are
two new functions with the exact same behaviors as the
\f[V]resolveFunc\f[R] and \f[V]rejectFunc\f[R] passed to the
\f[V]executor\f[R] function.
If calling the \f[V]then\f[R] method throws, then the current promise is
rejected with the thrown error.
.PP
In the last case, it means code like:
.IP
.nf
\f[C]
new Promise((resolve, reject) => {
  resolve(thenable);
});
\f[R]
.fi
.PP
Is roughly equivalent to:
.IP
.nf
\f[C]
new Promise((resolve, reject) => {
  try {
    thenable.then(
      (value) => resolve(value),
      (reason) => reject(reason),
    );
  } catch (e) {
    reject(e);
  }
});
\f[R]
.fi
.PP
Except that in the \f[V]resolve(thenable)\f[R] case:
.IP "1." 3
\f[V]resolve\f[R] is called synchronously, so that calling
\f[V]resolve\f[R] or \f[V]reject\f[R] again has no effect, even when the
handlers attached through \f[V]anotherPromise.then()\f[R] are not called
yet.
.IP "2." 3
The \f[V]then\f[R] method is called asynchronously, so that the promise
will never be instantly resolved if a thenable is passed.
.PP
Because \f[V]resolve\f[R] is called again with whatever
\f[V]thenable.then()\f[R] passes to it as \f[V]value\f[R], the resolver
function is able to flatten nested thenables, where a thenable calls its
\f[V]onFulfilled\f[R] handler with another thenable.
The effect is that the fulfillment handler of a real promise will never
receive a thenable as its fulfillment value.
.SH Examples
.SS Turning a callback-based API into a promise-based one
.PP
To provide a function with promise functionality, have it return a
promise by calling the \f[V]resolve\f[R] and \f[V]reject\f[R] functions
at the correct times.
.IP
.nf
\f[C]
function myAsyncFunction(url) {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open(\[dq]GET\[dq], url);
    xhr.onload = () => resolve(xhr.responseText);
    xhr.onerror = () => reject(xhr.statusText);
    xhr.send();
  });
}
\f[R]
.fi
.SS Effect of calling resolveFunc
.PP
Calling \f[V]resolveFunc\f[R] causes the promise to become resolved, so
that calling \f[V]resolveFunc\f[R] or \f[V]rejectFunc\f[R] again has no
effect.
However, the promise may be in any of the states: pending, fulfilled, or
rejected.
.PP
This \f[V]pendingResolved\f[R] promise is resolved the time it\[cq]s
created, because it has already been \[lq]locked in\[rq] to match the
eventual state of the inner promise, and calling \f[V]resolveOuter\f[R]
or \f[V]rejectOuter\f[R] or throwing an error later in the executor has
no effect on its eventual state.
However, the inner promise is still pending until 100ms later, so the
outer promise is also pending:
.IP
.nf
\f[C]
const pendingResolved = new Promise((resolveOuter, rejectOuter) => {
  resolveOuter(
    new Promise((resolveInner) => {
      setTimeout(() => {
        resolveInner(\[dq]inner\[dq]);
      }, 100);
    }),
  );
});
\f[R]
.fi
.PP
This \f[V]fulfilledResolved\f[R] promise becomes fulfilled the moment
it\[cq]s resolved, because it\[cq]s resolved with a non-thenable value.
However, when it\[cq]s created, it\[cq]s unresolved, because neither
\f[V]resolve\f[R] nor \f[V]reject\f[R] has been called yet.
An unresolved promise is necessarily pending:
.IP
.nf
\f[C]
const fulfilledResolved = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(\[dq]outer\[dq]);
  }, 100);
});
\f[R]
.fi
.PP
Calling \f[V]rejectFunc\f[R] obviously causes the promise to reject.
However, there are also two ways to cause the promise to instantly
become rejected even when the \f[V]resolveFunc\f[R] callback is called.
.IP
.nf
\f[C]
// 1. Resolving with the promise itself
const rejectedResolved1 = new Promise((resolve) => {
  // Note: resolve has to be called asynchronously,
  // so that the rejectedResolved1 variable is initialized
  setTimeout(() => resolve(rejectedResolved1)); // TypeError: Chaining cycle detected for promise #<Promise>
});

// 2. Resolving with an object which throws when accessing the \[ga]then\[ga] property
const rejectedResolved2 = new Promise((resolve) => {
  resolve({
    get then() {
      throw new Error(\[dq]Can\[aq]t get then property\[dq]);
    },
  });
});
\f[R]
.fi
.SH See also
.IP \[bu] 2
Polyfill of \f[V]Promise\f[R] in
\f[V]core-js\f[R] (https://github.com/zloirock/core-js#ecmascript-promise)
.IP \[bu] 2
Using promises
